name: release

on:
  push:
    tags-ignore:
      - '*-beta.*'

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          npm install npm@latest
          npm ci

      - name: Test
        run: npm run test

      - name: Compile
        run: npm run build

      - name: Publish
        run: npm publish
